"use client";

import { useState } from "react";
import { createCategory, deleteCategory, updateCategory } from "@/app/manage-actions";
import type { Category } from "@/types/category";

const inputClass = "mt-1.5 h-10 w-full rounded-xl border border-input bg-background px-3 text-[13px] outline-none transition-colors focus:border-ring focus:ring-2 focus:ring-ring/20";
function ErrorText({ message }: { message: string }) { return message ? <p className="mt-2 text-[13px] text-destructive" role="alert">{message}</p> : null; }

export default function CategoriesManager({ categories }: { categories: Category[] }) {
  const [editing, setEditing] = useState<Category | null>(null); const [creating, setCreating] = useState(false); const [error, setError] = useState(""); const [pending, setPending] = useState(false);
  function closeForm() { setCreating(false); setEditing(null); setError(""); }
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); setPending(true); const formData = new FormData(event.currentTarget); try { if (editing) await updateCategory(formData); else await createCategory(formData); closeForm(); } catch (actionError) { setError(actionError instanceof Error ? actionError.message : "Something went wrong"); } finally { setPending(false); } }
  async function remove(category: Category) { if (!confirm(`Delete ${category.name}? This cannot be undone.`)) return; setError(""); setPending(true); const formData = new FormData(); formData.set("id", category.id); try { await deleteCategory(formData); } catch (actionError) { setError(actionError instanceof Error ? actionError.message : "Something went wrong"); } finally { setPending(false); } }
  return <div className="space-y-4"><section className="overflow-hidden rounded-2xl border border-border bg-card"><header className="flex items-center justify-between gap-3 border-b border-border px-5 py-4"><div><h2 className="text-[15px] font-semibold">Work Areas</h2><p className="mt-1 text-[13px] text-muted-foreground">Labels used to group completed requests.</p></div><button type="button" onClick={() => { setCreating(true); setEditing(null); setError(""); }} className="h-9 rounded-full bg-primary px-4 text-[13px] font-medium text-primary-foreground hover:bg-[#108513]">Add work area</button></header><ul className="divide-y divide-border">{categories.map((category) => <li key={category.id} className="flex flex-wrap items-center gap-3 px-5 py-4"><span className="min-w-0 flex-1 truncate text-[13px] font-medium">{category.name}</span><div className="flex gap-1"><button type="button" onClick={() => { setEditing(category); setCreating(false); setError(""); }} className="rounded-full bg-[#FFB400]/15 px-3 py-1.5 text-xs font-medium text-[#a66f00] transition-colors hover:bg-[#FFB400]/25 dark:text-[#ffd166]">Edit</button><button type="button" disabled={pending} onClick={() => remove(category)} className="rounded-full px-3 py-1.5 text-xs font-medium text-destructive hover:bg-destructive/10">Delete</button></div></li>)}{!categories.length && <li className="px-5 py-8 text-center text-[13px] text-muted-foreground">No work areas yet.</li>}</ul></section>{(creating || editing) && <form onSubmit={submit} className="space-y-5 rounded-2xl border border-border bg-card p-5 sm:p-6"><h2 className="text-[15px] font-semibold">{editing ? `Edit ${editing.name}` : "New work area"}</h2>{editing && <input type="hidden" name="id" value={editing.id} />}<label className="block text-[13px] font-medium">Work area name<input name="name" required maxLength={80} defaultValue={editing?.name} className={inputClass} autoFocus /></label><ErrorText message={error} /><div className="flex gap-2"><button type="submit" disabled={pending} className="h-10 rounded-full bg-primary px-5 text-[13px] font-medium text-primary-foreground hover:bg-[#108513] disabled:opacity-60">{pending ? "Saving…" : editing ? "Save changes" : "Create work area"}</button><button type="button" onClick={closeForm} className="h-10 rounded-full border border-border px-5 text-[13px] font-medium hover:bg-muted">Cancel</button></div></form>}{!creating && !editing && <ErrorText message={error} />}</div>;
}
